### ISSUE TITLE
myst parser stripping one backslash from bare align equations 

### ISSUE THREAD

**Issue by phaustin** [ExecutableBookProject/MyST-NB#160] opened 2020-04-22 02:23 UTC
See the code in #159 for a demonstration.  Not sure if this an easy fix or would require a lot more from the parser.

**Comment by chrisjsewell** [comment] 2020-04-22 02:51
As discussed in https://github.com/ExecutableBookProject/MyST-NB/pull/159#issuecomment-617511866, this is essentially a duplicate of #126

**Closed by chrisjsewell** 2020-04-22 02:51 UTC
Labels: bug
