### ISSUE TITLE
Using an ipynb as the root (index) file

### ISSUE THREAD

**Issue by chrisjsewell** [ExecutableBookProject/MyST-NB#128] opened 2020-04-04 08:30 UTC
It is almost as if it is expecting `.md` extension by default and can't find the files specified in the `index.ipynb`.

_Originally posted by @mmcky in https://github.com/ExecutableBookProject/myst-nb.example-project/issues/3#issuecomment-608995444_

**Comment by mmcky** [comment] 2020-04-07 00:51
cc: @AakashGfude

**Comment by mmcky** [comment] 2020-04-07 01:21
@AakashGfude let's coordinate a fix for this around https://github.com/ExecutableBookProject/myst-nb.example-project

**Comment by mmcky** [comment] 2020-04-07 02:21
this seems to be getting issued within sphinx:
https://github.com/sphinx-doc/sphinx/blob/0ae1bf6f037010b5599d12196b155bbf2cece9ba/sphinx/directives/other.py#L131

**Comment by mmcky** [comment] 2020-04-07 02:28
This line in sphinx seems to be issuing the warning: https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/util/nodes.py#L427

**Comment by mmcky** [comment] 2020-04-07 02:35
In the case of `myst-nb.example-project` it looks like no extension is being applied

```bash
(Pdb) print(toctreenode['includefiles'])
['ar1_processes-MyST', 'finite_markov-MyST']
```

**Comment by mmcky** [comment] 2020-04-07 03:07
It seems to be triggering the exception on the second call of the ``inline_all_toctrees`` function.

**Comment by mmcky** [comment] 2020-04-07 03:15
@AakashGfude tried a few `pdb` runs -- and can't see why this Exception is getting triggered. Let me know if you have any ideas.

**Comment by AakashGfude** [comment] 2020-04-07 03:19
@mmcky , it is being triggered by this line on the second call of the `inline_all_toctress` :- 
https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/util/nodes.py#L413

The `cast` function from the `typing` module is throwing this error :- 
```
TypeError: __init__() got multiple values for argument 'outputs'
```

**Comment by mmcky** [comment] 2020-04-07 03:26
right - but what does that mean? There is no argument `outputs` right?

**Comment by mmcky** [comment] 2020-04-07 03:28
ah - you are a better `pdb` user than me `:-)`.

**Comment by AakashGfude** [comment] 2020-04-07 03:32
yeah, it's weird. I will try to compare the tree on the first pass when it was working vs. the tree on the second pass when it broke. Let's see if I can find any noticeable anomalies.

**Comment by mmcky** [comment] 2020-04-07 03:38
OK so this is also different to `myst-parser.example-project` in that there are no executed outputs for that `example` repo.

**Comment by mmcky** [comment] 2020-04-07 03:46
The xml representation of the `ar1_processes` document is:

[ar1_processes-MyST.txt](https://github.com/ExecutableBookProject/MyST-NB/files/4441924/ar1_processes-MyST.txt)

**Comment by mmcky** [comment] 2020-04-07 03:47
Is this because `sphinx` cast is against `nodes.document` and perhaps the output cell is not defined?

**Comment by mmcky** [comment] 2020-04-07 03:52
It is also interesting that `make html` doesn't use the function `inline_all_toctrees`

**Comment by AakashGfude** [comment] 2020-04-07 04:01
@mmcky  the error is not caused by the cast function apparently
```
tree = cast(nodes.document, tree.deepcopy())
```

but by the `deepcopy`  function in `tree.deepcopy()`

**Comment by mmcky** [comment] 2020-04-07 04:48
@AakashGfude the only difference I see in the `xml` is that the markup relating to `Cell` uses camelcase names when the rest of the xml uses lower case. Could this be breaking some `xml schema` when copying the document?

**Comment by mmcky** [comment] 2020-04-07 05:08
so `tree` is of type `docutils.nodes.document`.

It has inheritance from `class document(Root, Structural, Element):`

It seems that the class `Element` has a method `deepcopy`

```
    def copy(self):
        obj = self.__class__(rawsource=self.rawsource, **self.attributes)
        obj.document = self.document
        obj.source = self.source
        obj.line = self.line
        return obj

    def deepcopy(self):
        copy = self.copy()
        copy.extend([child.deepcopy() for child in self.children])
        return copy
```

but can't see why these copy methods except.

**Comment by mmcky** [comment] 2020-04-07 05:35
this may be related: https://github.com/ExecutableBookProject/myst-nb.example-project/issues/4 and will fix this first.

**Comment by mmcky** [comment] 2020-04-07 06:26
@AakashGfude, @choldgraf @chrisjsewell I am starting to wonder if this is because teach `markdown` cell in the notebook is being parsed by `myst_parser` independently. Is it possible the `tree` is malformed as it isn't a complete `doctree` causing the underlying copy method to fail?

**Comment by mmcky** [comment] 2020-04-07 06:38
@chrisjsewell can we compare the AST between `html` and `latex` to see how they differ?

**Comment by mmcky** [comment] 2020-04-07 06:40
re: code above in `docutils` we fail at:

```
copy.extend([child.deepcopy() for child in self.children])
```
one of the child objects doesn't `deepcopy`. Currently trying to figure out which one

**Closed** 2020-04-08 02:47 UTC
Labels: bug
